### ISSUE TITLE
Have some troubles.

### ISSUE THREAD

**Issue by xSalved** [Lutwidse/dexbot-aptos#1]
Hello sir. I'm not good programmer so i have a question. I've found your repo on github
https://github.com/Lutwidse/dexbot-aptos
So i tried to run the script but i have an error
I checked json response it says this. Maybe you can help me with this?
`Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\pythonProject7\main.py", line 105, in <module>
    txn_hash = rest_client.submit_transaction(account, payload)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\pythonProject7\main.py", line 40, in submit_transaction
    to_sign = bytes.fromhex(response.json()[2:])
TypeError: unhashable type: 'slice'`

JSON response:
`{
    "message": "parse request payload error: failed to parse \"string(U64)\": invalid type: integer `3000`, expected a string (occurred while parsing \"UserTransactionRequestInner\") (occurred while parsing \"EncodeSubmissionRequest\")",
    "error_code": "web_framework_error",
    "vm_error_code": null
}`

**Comment by xSalved** [comment]
when i'm trying through bcs it says:
`{'error': {'code': 400, 'message': 'Unexpected token \'�\', "�g����,S�<"... is not valid JSON'}}`

**Comment by lutwidse** [comment]
Hi, The issue is known as the RPC-side problem, so we have to wait for an update of Ankr's Aptos node or you can run a node yourself.
And imo, this bot is unwinnable because some Aptos botter remodeled their node, also they're considering a consensus mechanism. That's why I publicly opened this repo.

**Comment by xSalved** [comment]
> 

Thanks for your reply! I dont really care about win this bot or no, i just wanna see how it works and get some experience =)

**Comment by lutwidse** [comment]
Good! have fun :)

**Comment by Cosangeles777** [comment]
@Lutwidse 
"RPC-side problem, so we have to wait for an update of Ankr's Aptos node or you can run a node yourself."

how to run it yourself? What is bcs mode for? Does it work without bcs?
